// =============================================================================
// Phosphor 图标映射 — 集中管理 UI 用到的图标（design-taste skill：禁 emoji）
// 组件通过 <Ui.Icon name={I.gauge} /> 使用，图标来源唯一。
// =============================================================================
import {
  Gauge,
  ListChecks,
  MagnifyingGlass,
  Stack,
  SquaresFour,
  GearSix,
  ChatCircleDots,
  Terminal,
  Play,
  Pause,
  Stop,
  PaperPlaneTilt,
  X,
  Check,
  Warning,
  Info,
  ArrowRight,
  ArrowLeft,
  CaretRight,
  CaretDown,
  Plus,
  Trash,
  PencilSimple,
  ArrowClockwise,
  ArrowCounterClockwise,
  Database,
  FileCode,
  FileText,
  GitBranch,
  LinkSimple,
  Cube,
  Rocket,
  ShieldCheck,
  ArrowsDownUp,
  Lock,
  LockSimple,
  Eye,
  EyeSlash,
  Download,
  Upload,
  Clipboard,
  CheckCircle,
  XCircle,
  Circle,
  Question,
  Lightning,
  Clock,
  Calendar,
  User,
  Users,
  Bell,
  BellRinging,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  CaretDoubleLeft,
  CaretDoubleRight,
  Timer,
  Coins,
  ChartBar,
  Wallet,
  Wrench,
  GithubLogo,
  Star,
  ArrowSquareOut,
  PlugsConnected,
  Storefront,
} from '@phosphor-icons/react';

export const I = {
  gauge: Gauge,
  listChecks: ListChecks,
  search: MagnifyingGlass,
  stack: Stack,
  squares: SquaresFour,
  gear: GearSix,
  chat: ChatCircleDots,
  terminal: Terminal,
  play: Play,
  pause: Pause,
  stop: Stop,
  send: PaperPlaneTilt,
  close: X,
  check: Check,
  warn: Warning,
  info: Info,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  caretRight: CaretRight,
  caretDown: CaretDown,
  plus: Plus,
  trash: Trash,
  edit: PencilSimple,
  refresh: ArrowClockwise,
  undo: ArrowCounterClockwise,
  database: Database,
  fileCode: FileCode,
  fileText: FileText,
  branch: GitBranch,
  link: LinkSimple,
  cube: Cube,
  rocket: Rocket,
  shield: ShieldCheck,
  swap: ArrowsDownUp,
  lock: Lock,
  lockSimple: LockSimple,
  eye: Eye,
  eyeSlash: EyeSlash,
  download: Download,
  upload: Upload,
  clipboard: Clipboard,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  circle: Circle,
  question: Question,
  bolt: Lightning,
  clock: Clock,
  calendar: Calendar,
  user: User,
  users: Users,
  bell: Bell,
  bellRing: BellRinging,
  sliders: SlidersHorizontal,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  doubleLeft: CaretDoubleLeft,
  doubleRight: CaretDoubleRight,
  timer: Timer,
  coins: Coins,
  chartBar: ChartBar,
  wallet: Wallet,
  wrench: Wrench,
  github: GithubLogo,
  star: Star,
  arrowSquareOut: ArrowSquareOut,
  plugs: PlugsConnected,
  storefront: Storefront,
} as const;

export type IconName = keyof typeof I;
